# Generated by Django 2.2.6 on 2019-10-25 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Course name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('course_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Course owner')),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='course_students', to=settings.AUTH_USER_MODEL, verbose_name='Students')),
                ('teachers', models.ManyToManyField(blank=True, null=True, related_name='course_teachers', to=settings.AUTH_USER_MODEL, verbose_name='Teachers')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_date', 'name'],
            },
        ),
    ]
