# Generated by Django 2.2.6 on 2019-10-26 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_auto_20191026_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=128, verbose_name='Lecture theme')),
                ('lecture_file', models.FileField(upload_to='uploads/lectures/%Y/%m/%d')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lectures', to='course.Course', verbose_name='Course name')),
                ('lecture_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_lectures', to=settings.AUTH_USER_MODEL, verbose_name='Lecture owner')),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'ordering': ['-created_date', 'theme'],
            },
        ),
    ]
