# Generated by Django 2.2.6 on 2019-10-29 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hometask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_file', models.FileField(upload_to='uploads/homeworks/%Y/%m/%d')),
                ('mark', models.PositiveSmallIntegerField(null=True, verbose_name='Mark')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('hometask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_homeworks_for_task', to='hometask.Hometask', verbose_name='Task')),
                ('homework_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Homework owner')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homeworks',
                'ordering': ['-created_date', 'homework_owner'],
            },
        ),
    ]
