# Generated by Django 2.2.6 on 2019-10-31 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_comments', to=settings.AUTH_USER_MODEL, verbose_name='Comment owner')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_comments', to='homework.Homework', verbose_name='Homework')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_date', 'homework'],
            },
        ),
    ]
