# Generated by Django 2.2.6 on 2019-10-28 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hometask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_body', models.TextField(verbose_name='Task')),
                ('possible_max_mark', models.PositiveSmallIntegerField(verbose_name='Max mark for the task')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_tasks', to='lecture.Lecture', verbose_name='Lecture theme')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_date', 'lecture'],
            },
        ),
    ]
